services:
  - type: web
    name: leave-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:Ju5taqua2026@db.hveokpjabwcbtvjaiygy.supabase.co:5432/postgres